### ISSUE TITLE
Request for Ownership of BBBaden-Moodle-userscripts

### ISSUE THREAD

**Issue by Pianonic** [black-backdoor/black-backdoor#1]
Hi @black-backdoor,

I noticed that you recently archived the [BBBaden-Moodle-userscripts](https://github.com/BBBaden-Moodle-userscripts) repository. I am still actively developing extensions and fixes for it and would like to request that you reactivate the repository and transfer ownership to me, so I can maintain the Organization.

Would be great, because I use the extensions every day. 

Thank you very much for your consideration!

Best regards

**Comment by black-backdoor** [comment]
Sent an Invitation with full Owner access
